In [2]:
import pandas as pd 

df = pd.read_csv("movies_metadata.csv")
df.head()

C:\Users\huuda\AppData\Local\Temp\ipykernel_34776\1145824585.py:3: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("movies_metadata.csv")

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0

In [3]:
df.columns

Index(['adult', 'belongs_to_collection', 'budget', 'genres', 'homepage', 'id',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'video',
       'vote_average', 'vote_count'],
      dtype='object')

In [5]:
columns_nonused = ["adult", "belongs_to_collection", "budget", "homepage", "original_title", "popularity", "production_companies", "production_countries", "revenue", "spoken_languages", "status", "vote_count", "video", "imdb_id"]
movies = df.drop(columns= columns_nonused)
movies.head()

,genres,id,original_language,overview,poster_path,release_date,runtime,tagline,title,vote_average
0,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",862,en,"Led by Woody, Andy's toys live happily in his ...",/rhIRbceoE9lR4veEXuwCC2wARtG.jpg,1995-10-30,81.0,NaN,Toy Story,7.7
1,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",8844,en,When siblings Judy and Peter discover an encha...,/vzmL6fP7aPKNKPRTFnZmiUfciyV.jpg,1995-12-15,104.0,Roll the dice and unleash the excitement!,Jumanji,6.9
2,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",15602,en,A family wedding reignites the ancient feud be...,/6ksm1sjKMFLbO7UY2i6G1ju9SML.jpg,1995-12-22,101.0,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,6.5
3,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",31357,en,"Cheated on, mistreated and stepped on, the wom...",/16XOMpEaLWkrcPqSQqhTmeJuqQl.jpg,1995-12-22,127.0,Friends are the people who let you be yourself...,Waiting to Exhale,6.1
4,"[{'id': 35, 'name': 'Comedy'}]",11862,en,Just when George Banks has recovered from his ...,/e64sOI48hQXyru7naBFyssKFxVd.jpg,1995-02-10,106.0,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,5.7

In [6]:
columns_rename = {"overview": "description", "vote_average": "rating", "runtime": "duration"}
movies = movies.rename(columns= columns_rename)
movies.head()

,genres,id,original_language,description,poster_path,release_date,duration,tagline,title,rating
0,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",862,en,"Led by Woody, Andy's toys live happily in his ...",/rhIRbceoE9lR4veEXuwCC2wARtG.jpg,1995-10-30,81.0,NaN,Toy Story,7.7
1,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",8844,en,When siblings Judy and Peter discover an encha...,/vzmL6fP7aPKNKPRTFnZmiUfciyV.jpg,1995-12-15,104.0,Roll the dice and unleash the excitement!,Jumanji,6.9
2,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",15602,en,A family wedding reignites the ancient feud be...,/6ksm1sjKMFLbO7UY2i6G1ju9SML.jpg,1995-12-22,101.0,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,6.5
3,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",31357,en,"Cheated on, mistreated and stepped on, the wom...",/16XOMpEaLWkrcPqSQqhTmeJuqQl.jpg,1995-12-22,127.0,Friends are the people who let you be yourself...,Waiting to Exhale,6.1
4,"[{'id': 35, 'name': 'Comedy'}]",11862,en,Just when George Banks has recovered from his ...,/e64sOI48hQXyru7naBFyssKFxVd.jpg,1995-02-10,106.0,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,5.7

In [7]:
import ast

def extract_genres(genres_str):
    try:
        genres_list = ast.literal_eval(genres_str)  # parse string → list of dict
        return ', '.join([g['name'] for g in genres_list])
    except:
        return ''

movies['genres'] = movies['genres'].apply(extract_genres)

# Kiểm tra kết quả
movies['genres'].head()

0     Animation, Comedy, Family
1    Adventure, Fantasy, Family
2               Romance, Comedy
3        Comedy, Drama, Romance
4                        Comedy
Name: genres, dtype: object

In [8]:
movies.head()

,genres,id,original_language,description,poster_path,release_date,duration,tagline,title,rating
0,"Animation, Comedy, Family",862,en,"Led by Woody, Andy's toys live happily in his ...",/rhIRbceoE9lR4veEXuwCC2wARtG.jpg,1995-10-30,81.0,NaN,Toy Story,7.7
1,"Adventure, Fantasy, Family",8844,en,When siblings Judy and Peter discover an encha...,/vzmL6fP7aPKNKPRTFnZmiUfciyV.jpg,1995-12-15,104.0,Roll the dice and unleash the excitement!,Jumanji,6.9
2,"Romance, Comedy",15602,en,A family wedding reignites the ancient feud be...,/6ksm1sjKMFLbO7UY2i6G1ju9SML.jpg,1995-12-22,101.0,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,6.5
3,"Comedy, Drama, Romance",31357,en,"Cheated on, mistreated and stepped on, the wom...",/16XOMpEaLWkrcPqSQqhTmeJuqQl.jpg,1995-12-22,127.0,Friends are the people who let you be yourself...,Waiting to Exhale,6.1
4,Comedy,11862,en,Just when George Banks has recovered from his ...,/e64sOI48hQXyru7naBFyssKFxVd.jpg,1995-02-10,106.0,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,5.7

In [10]:
movies.isna().sum()

genres                   0
id                       0
original_language       11
description            954
poster_path            386
release_date            87
duration               263
tagline              25054
title                    6
rating                   6
dtype: int64

In [11]:

cols_to_check = ['genres', 'original_language', 'description', 
                 'poster_path', 'release_date', 'duration', 
                 'title', 'rating']

movies_clean = movies.dropna(subset=cols_to_check)

print(f"Before: {len(movies)} rows")
print(f"After:   {len(movies_clean)} rows")
print(f"Deleted: {len(movies) - len(movies_clean)} rows")

Before: 45466 rows
After:   44118 rows
Deleted: 1348 rows

In [13]:
movies_clean.isna().sum()

genres                   0
id                       0
original_language        0
description              0
poster_path              0
release_date             0
duration                 0
tagline              23738
title                    0
rating                   0
dtype: int64

In [16]:
movies_clean = movies_clean.drop(columns="tagline")
movies_clean.head()

,genres,id,original_language,description,poster_path,release_date,duration,title,rating
0,"Animation, Comedy, Family",862,en,"Led by Woody, Andy's toys live happily in his ...",/rhIRbceoE9lR4veEXuwCC2wARtG.jpg,1995-10-30,81.0,Toy Story,7.7
1,"Adventure, Fantasy, Family",8844,en,When siblings Judy and Peter discover an encha...,/vzmL6fP7aPKNKPRTFnZmiUfciyV.jpg,1995-12-15,104.0,Jumanji,6.9
2,"Romance, Comedy",15602,en,A family wedding reignites the ancient feud be...,/6ksm1sjKMFLbO7UY2i6G1ju9SML.jpg,1995-12-22,101.0,Grumpier Old Men,6.5
3,"Comedy, Drama, Romance",31357,en,"Cheated on, mistreated and stepped on, the wom...",/16XOMpEaLWkrcPqSQqhTmeJuqQl.jpg,1995-12-22,127.0,Waiting to Exhale,6.1
4,Comedy,11862,en,Just when George Banks has recovered from his ...,/e64sOI48hQXyru7naBFyssKFxVd.jpg,1995-02-10,106.0,Father of the Bride Part II,5.7

In [17]:
movies_clean.to_csv("movies_final.csv", index = False)

In [ ]:
movies